### PR TITLE
made FILTERS_DEFAULT_OPEN explanation more clear

### PR DESCRIPTION
**Pull request by pierreloicq**

### CODE REVIEW

**Comment by pierreloicq** [comment]
Wouln't be nice to put "FILTERS_DEFAULT_OPEN : true" by default ?

**Comment by camillemonchicourt** [comment]
Thanks. Yes Default True sounds good to me.

**Comment by gutard** [comment]
Thanks for this PR. However, it refers to sliders whereas filters can be checkboxes too. Moreover, the fact that sliders are not correctly initialized when FILTERS_DEFAULT_OPEN is not set is a bug and should not be documented.

Changing defaults along the way is not a good idea. The behaviour of existing installations will change unexpectedly on upgrade.

**Comment by camillemonchicourt** [comment]
The suggestion is good as the actual option details are not clear but just need to be changed for something like "If true, the filters values will be expanded by default"

**Pull request closed without merging**
